version: "3.8"
services:
  web:
    build:
      context: ./wasm
      dockerfile: Dockerfile.web
    image: minislug-web
    container_name: minislug-web
    ports:
      - "8081:80"
    restart: always
    deploy:
      resources:
        limits:
          memory: 50M
